In [5]:
import copy
Matrices={" "}

class MatricesTree :
    #1- intilizing the Tree Node
    def  __init__ (self , matrix: (),parent=None):
        self.parent=parent #giving the parent None Value 
        self.matrix=matrix 
        self.newStates=[]  #Children List
        self.h = h(matrix)  # Distance to goal node
        self.g = 0  # Distance to start node
        self.f = 0  # Total cost
     # Compare nodes
    def isEqual(self, other):
        return self.matrix == other.matrix

    # Sort nodes
    def __lt__(self, other):
        return self.f < other.f

    # Print node
    def __repr__(self):
        return ('({0},{1})'.format(self.matrix, self.f))
        
    #2
    def addNewState (self , state):# adding new child to Node
        self.newStates.append(state)
    #3
    def updatingParent (self , state): # updating the parent of the child
        state.parent=self
    
    #4
    def getingPath(self):#printing the path of the GOAL
        PathLen=0 #the states Number to the Goal
        Path=[ ] #saving the path in an array        
        while self.parent != None :
            Path.append(self.matrix)    
            self=self.parent
            PathLen+=1
        print("Cost Path is :"+ str (PathLen-1))
        print("______The   GOAL is______   \n"+str(Path[-1])) #
        print("The Path : ")
        print("1.   \n"+str(self.matrix))
        print("\n")
        x=2
        for i in range(PathLen-1, -1, -1): #printing the array in revers from23    
            if(x<PathLen): 
                print(str(x)+".   \n"+str(Path[i])+"\n")
            x+=1

#-------------------------------------------------------------------------------------------------------------------------------

def h(x: ()):
    y=copy.deepcopy(x)
    row=len(y)
    col=len(y[0])
    heuristic=0
    for m in range(row):
        for n in range(col):
            StepsNum=y[m][n]-1
            NumRow=int (StepsNum/row)
            NumCol=StepsNum%col
            temp=y[m][n]
            y[m][n]=y[NumRow][NumCol]
            y[NumRow][NumCol]=temp            
            TotalSteps=abs(m-NumRow)+abs(n-NumCol)
            heuristic+=TotalSteps
    return heuristic

#-------------------------------------------------------------------------------------------------------------------------------

def successor(matrix: ()):
    list=[]
    i=0
    while i<len(matrix):
        j=0
        while j<len(matrix[i]):
            if i+1<len(matrix):
                B=copy.deepcopy(matrix)
                temp = B[i][j]
                B[i][j]=B[i+1][j]
                B[i+1][j]=temp
                list.append(B)
            if j+1<len(matrix[i]):
                A = copy.deepcopy(matrix)
                temp = A[i][j]
                A[i][j]=A[i][j+1]
                A[i][j+1]=temp
                list.append(A)
            j=j+1
        i=i+1
    return list
#-------------------------------------------------------------------------------------------------------------------------------

def IsNewstate (matrix: ()) :
    ColAndRowLen=len(matrix)
    MatrixString=''
    for n in range(ColAndRowLen):
        for m in range(ColAndRowLen):
            temp=MatrixString
            MatrixString=" "+str(matrix[m][n])
            MatrixString+=temp
    lenBeforeAdding=len(Matrices)                                
    Matrices.add(MatrixString)                
    lenAfterAdding=len(Matrices)
    if lenBeforeAdding != lenAfterAdding:
        return True
    else:
        return False

#-------------------------------------------------------------------------------------------------------------------------------

def isGoal (matrix: ()):
    x=1
    i=0
    while i<len(matrix):
        j=0
        while j<len(matrix[i]):
            if (matrix[i][j]!=x):
                return False
            x+=1
            j=j+1
        i=i+1
    return True

#-------------------------------------------------------------------------------------------------------------------------------
from queue import PriorityQueue
def AStar (matrix: ()) :
    queue =PriorityQueue()
    newNode=MatricesTree(matrix)
    queue.put(newNode)
    countStates=1
    flag=0
    while queue.empty() != True and flag == 0:
        currState=queue.get()
        if isGoal(currState.matrix)==True :
            flag=1
            currState.getingPath()
            return "States number = " + str(countStates)
        
        if flag==0:
            stateChildren=successor(currState.matrix)
            for child in stateChildren:               
                if IsNewstate(child) == True:
                    new=MatricesTree(child)
                    new.parent=currState
                    currState.addNewState(new)
                    currState.updatingParent(new)
                    new.g=currState.g+1
                    new.f=new.g+new.h  
                    queue.put(new)
        countStates+=1
#-------------------------------------------------------------------------------------------------------------------------------
import numpy as np
input = np.loadtxt("3x3_1.txt", dtype='i', delimiter=' ')
AStar(input)

Cost Path is :12
______The   GOAL is______   
[[5 9 6]
 [8 4 7]
 [2 3 1]]
The Path : 
1.   
[[8 9 6]
 [5 4 7]
 [2 3 1]]


2.   
[[5 9 6]
 [8 4 7]
 [2 3 1]]

3.   
[[5 9 6]
 [2 4 7]
 [8 3 1]]

4.   
[[2 9 6]
 [5 4 7]
 [8 3 1]]

5.   
[[2 9 6]
 [5 4 1]
 [8 3 7]]

6.   
[[2 4 6]
 [5 9 1]
 [8 3 7]]

7.   
[[2 4 6]
 [5 3 1]
 [8 9 7]]

8.   
[[2 4 6]
 [5 3 1]
 [8 7 9]]

9.   
[[2 4 6]
 [5 1 3]
 [8 7 9]]

10.   
[[2 4 6]
 [1 5 3]
 [8 7 9]]

11.   
[[4 2 6]
 [1 5 3]
 [8 7 9]]

12.   
[[1 2 6]
 [4 5 3]
 [8 7 9]]



'States number = 927'