In [56]:
import copy

class MatricesTree :
    #1- intilizing the Tree Node
    def  __init__ (self , matrix: ()):
        self.g=0
        self.matrix=matrix 
#-------------------------------------------------------------------------------------------------------------------------------

def successor(matrix: ()):
    list=[]
    i=0
    while i<len(matrix):
        j=0
        while j<len(matrix[i]):
            if i+1<len(matrix):
                B=copy.deepcopy(matrix)
                temp = B[i][j]
                B[i][j]=B[i+1][j]
                B[i+1][j]=temp
                list.append(B)
            if j+1<len(matrix[i]):
                A = copy.deepcopy(matrix)
                temp = A[i][j]
                A[i][j]=A[i][j+1]
                A[i][j+1]=temp
                list.append(A)
            j=j+1
        i=i+1
    return list

#-------------------------------------------------------------------------------------------------------------------------------

def isGoal (matrix: ()):
    x=1
    i=0
    while i<len(matrix):
        j=0
        while j<len(matrix[i]):
            if (matrix[i][j]!=x):
                return False
            x+=1
            j=j+1
        i=i+1
    return True

#-------------------------------------------------------------------------------------------------------------------------------
StatesNum=0
def DFS(Matrix: (),Stack: (),Depth: ()):
    global StatesNum
    StatesNum+=1
    StackLen=len(Stack) 
    if (StackLen==Depth):
        if(isGoal(Stack[-1].matrix)==True):
            return Stack
        else:
            temp=[]
            return temp
    elif(StackLen==0):
        Stack.append(MatricesTree(Matrix))
        return (DFS(Matrix,Stack,Depth))
    else:
        currState=Stack[-1]
        stateChildren=successor(currState.matrix)
        for child in stateChildren:               
            new=MatricesTree(child)
            new.g=Stack[-1].g+1
            Stack.append(new)
            newStack=DFS(Matrix,Stack,Depth)
            if(len(newStack) != 0):
                return(newStack)
            Stack.pop()
    temp=[]
    return (temp)
#-------------------------------------------------------------------------------------------------------------------------------def iterative_deepening (Matrix: (),Depth:()):
def IDDS(Matrix: (),Depth: ()):
    
    for index in range(Depth):
        Stack=[]
        Path=DFS(Matrix,Stack,index+1)
        PathLen=len(Path)
        if(PathLen!=0):
            print("States number = " + str(StatesNum))
            print("Cost Path is :"+ str (PathLen-1))
            print("______The   GOAL is______   \n"+str(Path[-1].matrix)) #
            print("The Path : ")
            x=1
            for i in Path:
                if(x<=PathLen): 
                    a_str=".   \n"
                    print(str(x)+a_str +str(i.matrix))
                    print("\n")
                x+=1
            break
#-------------------------------------------------------------------------------------------------------------------------------import numpy as np
print("Example1 : \n")
Example1=np.array([[2,1,3],[4,5,6],[7,8,9]])
IDDS(Example1,20)

print("Example2 : \n")
Example2=np.array([[1,3,2],[5,4,6],[7,8,9]])
IDDS(Example2,20)

print("Example3 : \n")
Example3=np.array([[1,3,2],[5,4,6],[7,9,8]])
IDDS(Example3,20)


Example1 : 

States number = 6
Cost Path is :1
______The   GOAL is______   
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The Path : 
1.   
[[2 1 3]
 [4 5 6]
 [7 8 9]]


2.   
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Example2 : 

States number = 71
Cost Path is :2
______The   GOAL is______   
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The Path : 
1.   
[[1 3 2]
 [5 4 6]
 [7 8 9]]


2.   
[[1 2 3]
 [5 4 6]
 [7 8 9]]


3.   
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Example3 : 

States number = 810
Cost Path is :3
______The   GOAL is______   
[[1 2 3]
 [4 5 6]
 [7 8 9]]
The Path : 
1.   
[[1 3 2]
 [5 4 6]
 [7 9 8]]


2.   
[[1 2 3]
 [5 4 6]
 [7 9 8]]


3.   
[[1 2 3]
 [4 5 6]
 [7 9 8]]


4.   
[[1 2 3]
 [4 5 6]
 [7 8 9]]


